using RecallCommander.Application.Attempts;
using RecallCommander.Infrastructure.FileSystem;
using RecallCommander.IntegrationTests.Support;
using RecallCommander.Markdown.Parsing;
using Xunit;

namespace RecallCommander.IntegrationTests.Integration;

/// <summary>
/// Attempt parsing against real files on disk: real filesystem, real parser,
/// production service wiring below the CLI.
/// </summary>
public sealed class AttemptParsingTests : IDisposable
{
    private readonly TestWorkspace _workspace = new();
    private readonly ValidateAttemptService _service = new(new PhysicalFileSystem(), new AttemptParser());

    private string AttemptsDirectory => Path.Combine(_workspace.Root, "Attempts");

    public void Dispose() => _workspace.Dispose();

    [Fact]
    public void Parses_a_completed_attempt_file_and_preserves_question_order()
    {
        string path = _workspace.WriteFile(
            AttemptsDirectory,
            "assessment-2026-07-17-001.attempt.md",
            """
            ---
            type: assessment
            title: Assessment 2026-07-17
            created: 2026-07-17T18:00:00
            question_count: 3
            ---

            # Assessment 2026-07-17

            This assessment was generated by Recall Commander.

            ---

            ## Question 1

            What is boxing in C#?

            ### Answer

            Boxing wraps a value type in a heap object.

            ---

            ## Question 2

            Explain how garbage collection works in .NET.

            Your answer should include generations and why they exist.

            ### Answer

            The GC frees unreachable objects.

            Objects start in generation 0 and survivors move up, because most objects die young.

            ---

            ## Question 3

            What is the CLR?

            ### Answer
            """);

        ValidateAttemptResult result = _service.Validate(path);

        Assert.Equal(ValidateAttemptStatus.Valid, result.Status);
        Assert.Equal("Assessment 2026-07-17", result.Attempt!.Title);
        Assert.Equal(
            [
                "What is boxing in C#?",
                "Explain how garbage collection works in .NET.\n\nYour answer should include generations and why they exist.",
                "What is the CLR?",
            ],
            result.Attempt.Questions.Select(question => question.Prompt));
        Assert.Contains("generation 0", result.Attempt.Questions[1].Answer);
        Assert.False(result.Attempt.Questions[2].IsAnswered);
    }

    [Fact]
    public void Recovers_after_a_malformed_section_and_reports_every_problem()
    {
        string path = _workspace.WriteFile(
            AttemptsDirectory,
            "broken.attempt.md",
            """
            ---
            type: assessment
            title: Assessment
            created: 2026-07-17T18:00:00
            ---

            ## Question 1

            First prompt?

            ---

            ## Question 2

            ### Answer

            An answer to a missing prompt.

            ---

            ## Question 3

            Third prompt?

            ### Answer

            A perfectly fine answer.
            """);

        ValidateAttemptResult result = _service.Validate(path);

        // Question 1 is missing its Answer heading (line 7) and question 2
        // has no prompt (line 13); question 3 parsed cleanly after both.
        Assert.Equal(ValidateAttemptStatus.Invalid, result.Status);
        Assert.Equal(2, result.Diagnostics.Count);
        Assert.Equal(7, result.Diagnostics[0].LineNumber);
        Assert.Contains("Missing '### Answer' heading", result.Diagnostics[0].Message);
        Assert.Equal(13, result.Diagnostics[1].LineNumber);
        Assert.Contains("no prompt text", result.Diagnostics[1].Message);
    }

    [Fact]
    public void The_result_locates_problems_by_file_and_line()
    {
        string path = _workspace.WriteFile(
            AttemptsDirectory,
            "unanswered.attempt.md",
            """
            ---
            type: assessment
            title: Assessment
            created: 2026-07-17T18:00:00
            ---

            ## Question 1

            First prompt?
            """);

        ValidateAttemptResult result = _service.Validate(path);

        Assert.Equal(ValidateAttemptStatus.Invalid, result.Status);
        Assert.Equal(path, result.FilePath);
        Assert.Equal(7, Assert.Single(result.Diagnostics).LineNumber);
    }

    [Fact]
    public void Reports_a_missing_file_without_touching_the_parser()
    {
        ValidateAttemptResult result = _service.Validate(Path.Combine(AttemptsDirectory, "nope.md"));

        Assert.Equal(ValidateAttemptStatus.FileNotFound, result.Status);
    }
}
