using Xunit;
using RecallCommander.Domain;
using RecallCommander.Markdown.Writing;

namespace RecallCommander.Markdown.Tests;

public sealed class AssessmentRendererTests
{
    private static readonly DateTimeOffset CreatedAt =
        new(2026, 7, 16, 18, 0, 0, TimeSpan.Zero);

    private readonly AssessmentRenderer _renderer = new();

    [Fact]
    public void Renders_the_documented_assessment_format()
    {
        var assessment = new Assessment("C# Assessment", CreatedAt,
        [
            new AssessmentQuestion("What is boxing in C#?"),
            new AssessmentQuestion("Explain how garbage collection works."),
            new AssessmentQuestion("Why can boxing negatively affect performance?"),
        ]);

        var content = _renderer.Render(assessment);

        const string expected =
            """
            ---
            type: assessment
            title: C# Assessment
            created: 2026-07-16T18:00:00
            question_count: 3
            ---

            # C# Assessment

            This assessment was generated by Recall Commander.

            ---

            ## Question 1

            What is boxing in C#?

            ---

            ## Question 2

            Explain how garbage collection works.

            ---

            ## Question 3

            Why can boxing negatively affect performance?

            """;

        Assert.Equal(expected.ReplaceLineEndings("\n"), content.Markdown);
    }

    [Fact]
    public void Uses_the_assessment_slug_and_directory()
    {
        var assessment = new Assessment("Title", CreatedAt, [new AssessmentQuestion("Prompt?")]);

        var content = _renderer.Render(assessment);

        Assert.Equal("assessment", content.Slug);
        Assert.Equal("Assessments", content.DirectoryName);
    }

    [Fact]
    public void Preserves_multiline_prompt_markdown()
    {
        var prompt = "Explain garbage collection.\n\nYour answer should include:\n\n- generations\n- the large object heap";
        var assessment = new Assessment("Title", CreatedAt, [new AssessmentQuestion(prompt)]);

        var content = _renderer.Render(assessment);

        Assert.Contains(prompt, content.Markdown);
    }
}
