using Xunit;
using RecallCommander.Domain;
using RecallCommander.Markdown.Writing;

namespace RecallCommander.Markdown.Tests;

public sealed class AssessmentRendererTests
{
    private const string ArtifactId = "assessment-2026-07-16-001";

    private static readonly DateTimeOffset CreatedAt =
        new(2026, 7, 16, 18, 0, 0, TimeSpan.Zero);

    private readonly AssessmentRenderer _renderer = new();

    [Fact]
    public void Renders_the_documented_assessment_format()
    {
        var assessment = new Assessment("C# Assessment", CreatedAt,
        [
            new AssessmentQuestion("What is boxing in C#?"),
            new AssessmentQuestion("Explain how garbage collection works."),
            new AssessmentQuestion("Why can boxing negatively affect performance?"),
        ]);

        var markdown = _renderer.Render(assessment, ArtifactId);

        const string expected =
            """
            ---
            type: assessment
            id: assessment-2026-07-16-001
            title: C# Assessment
            created: 2026-07-16T18:00:00
            question_count: 3
            ---

            # C# Assessment

            This assessment was generated by Recall Commander.

            ---

            ## Question 1

            What is boxing in C#?

            ### Answer

            ---

            ## Question 2

            Explain how garbage collection works.

            ### Answer

            ---

            ## Question 3

            Why can boxing negatively affect performance?

            ### Answer

            """;

        Assert.Equal(expected.ReplaceLineEndings("\n"), markdown);
    }

    [Fact]
    public void Frontmatter_id_is_the_artifact_id_it_was_rendered_with()
    {
        var assessment = new Assessment("Title", CreatedAt, [new AssessmentQuestion("Prompt?")]);

        var markdown = _renderer.Render(assessment, "assessment-2026-07-16-042");

        Assert.Contains("\nid: assessment-2026-07-16-042\n", markdown);
    }

    [Fact]
    public void Uses_the_assessment_slug_and_directory()
    {
        Assert.Equal("assessment", _renderer.Slug);
        Assert.Equal("Assessments", _renderer.DirectoryName);
    }

    [Fact]
    public void Preserves_multiline_prompt_markdown()
    {
        var prompt = "Explain garbage collection.\n\nYour answer should include:\n\n- generations\n- the large object heap";
        var assessment = new Assessment("Title", CreatedAt, [new AssessmentQuestion(prompt)]);

        var markdown = _renderer.Render(assessment, ArtifactId);

        Assert.Contains(prompt, markdown);
    }
}
