using Xunit;
using RecallCommander.Domain;
using RecallCommander.Markdown.Parsing;
using RecallCommander.Markdown.Writing;

namespace RecallCommander.Markdown.Tests;

public sealed class AttemptParserTests
{
    private readonly AttemptParser _parser = new();

    private const string Frontmatter =
        """
        ---
        type: assessment
        title: C# Assessment
        created: 2026-07-17T18:00:00
        ---
        """;

    [Fact]
    public void Parses_a_valid_attempt()
    {
        var markdown =
            $"""
            {Frontmatter}

            # C# Assessment

            This assessment was generated by Recall Commander.

            ---

            ## Question 1

            What is boxing in C#?

            ### Answer

            Boxing wraps a value type in an object on the heap.
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Empty(result.Diagnostics);
        Assert.Equal("C# Assessment", result.Attempt.Title);
        Assert.Equal(new DateTimeOffset(2026, 7, 17, 18, 0, 0, TimeSpan.Zero), result.Attempt.CreatedAtUtc);

        var question = Assert.Single(result.Attempt.Questions);
        Assert.Equal("What is boxing in C#?", question.Prompt);
        Assert.Equal("Boxing wraps a value type in an object on the heap.", question.Answer);
    }

    [Fact]
    public void Parses_multiple_questions_in_document_order()
    {
        var markdown =
            $"""
            {Frontmatter}

            # C# Assessment

            ---

            ## Question 1

            First prompt?

            ### Answer

            First answer.

            ---

            ## Question 2

            Second prompt?

            ### Answer

            Second answer.

            ---

            ## Question 3

            Third prompt?

            ### Answer

            Third answer.
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Equal(
            ["First prompt?", "Second prompt?", "Third prompt?"],
            result.Attempt.Questions.Select(question => question.Prompt));
        Assert.Equal(
            ["First answer.", "Second answer.", "Third answer."],
            result.Attempt.Questions.Select(question => question.Answer));
    }

    [Fact]
    public void Preserves_multiline_answers()
    {
        var answer =
            """
            Boxing converts a value type into an object.

            The runtime allocates a new object on the heap and copies the value into it.

            Unboxing extracts the value back out.
            """;

        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            What is boxing in C#?

            ### Answer

            {answer}
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Equal(answer, Assert.Single(result.Attempt.Questions).Answer);
    }

    [Fact]
    public void Preserves_markdown_inside_answers()
    {
        var answer =
            """
            Boxing has **two** costs:

            - a heap allocation
            - a copy of the value

            #### Example

            ```csharp
            object boxed = 42;
            ```
            """;

        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            What is boxing in C#?

            ### Answer

            {answer}
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Equal(answer, Assert.Single(result.Attempt.Questions).Answer);
    }

    [Fact]
    public void Empty_answers_are_valid()
    {
        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            First prompt?

            ### Answer

            ---

            ## Question 2

            Second prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.All(result.Attempt.Questions, question =>
        {
            Assert.Equal("", question.Answer);
            Assert.False(question.IsAnswered);
        });
    }

    [Fact]
    public void Missing_answer_heading_is_an_error()
    {
        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            What is boxing in C#?
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(7, diagnostic.LineNumber);
        Assert.Contains("Missing '### Answer' heading", diagnostic.Message);
    }

    [Fact]
    public void Collects_every_error_instead_of_stopping_at_the_first()
    {
        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            First prompt?

            ---

            ## Question 2

            Second prompt?
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Equal(2, result.Diagnostics.Count);
        Assert.Equal(7, result.Diagnostics[0].LineNumber);
        Assert.Equal(13, result.Diagnostics[1].LineNumber);
    }

    [Fact]
    public void Missing_frontmatter_is_an_error()
    {
        var markdown =
            """
            # C# Assessment

            ## Question 1

            What is boxing?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(1, diagnostic.LineNumber);
        Assert.Contains("Missing assessment frontmatter", diagnostic.Message);
    }

    [Fact]
    public void Unexpected_document_type_is_an_error()
    {
        var markdown =
            """
            ---
            type: review
            title: T
            created: 2026-07-17T18:00:00
            ---

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Contains(result.Diagnostics, diagnostic =>
            diagnostic.Message.Contains("Unexpected document type 'review'"));
    }

    [Fact]
    public void Missing_created_timestamp_is_an_error()
    {
        var markdown =
            """
            ---
            type: assessment
            title: T
            ---

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Contains(result.Diagnostics, diagnostic =>
            diagnostic.Message.Contains("missing required field 'created'"));
    }

    [Fact]
    public void Invalid_created_timestamp_is_an_error()
    {
        var markdown =
            """
            ---
            type: assessment
            title: T
            created: yesterday
            ---

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Contains(result.Diagnostics, diagnostic =>
            diagnostic.Message.Contains("Invalid 'created' timestamp 'yesterday'"));
    }

    [Fact]
    public void Document_without_questions_is_an_error()
    {
        var markdown =
            $"""
            {Frontmatter}

            # C# Assessment

            No questions here.
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Contains(result.Diagnostics, diagnostic =>
            diagnostic.Message.Contains("No questions found"));
    }

    [Fact]
    public void Question_without_prompt_text_is_an_error()
    {
        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            ### Answer

            An answer without a question.
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(7, diagnostic.LineNumber);
        Assert.Contains("no prompt text", diagnostic.Message);
    }

    [Fact]
    public void Answer_heading_outside_a_question_is_an_error()
    {
        var markdown =
            $"""
            {Frontmatter}

            ### Answer

            Stray answer.

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(7, diagnostic.LineNumber);
        Assert.Contains("outside a question section", diagnostic.Message);
    }

    [Fact]
    public void Falls_back_to_the_heading_title_when_frontmatter_has_none()
    {
        var markdown =
            """
            ---
            type: assessment
            created: 2026-07-13T20:15:00
            ---

            # C# Memory Management Assessment

            ## Question 1

            What is boxing in C#?

            ### Answer

            Boxing is when a value type is converted into an object.
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Equal("C# Memory Management Assessment", result.Attempt.Title);
    }

    [Fact]
    public void Missing_title_everywhere_is_an_error()
    {
        var markdown =
            """
            ---
            type: assessment
            created: 2026-07-17T18:00:00
            ---

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Contains(result.Diagnostics, diagnostic => diagnostic.Message.Contains("Missing title"));
    }

    [Fact]
    public void A_second_answer_heading_belongs_to_the_answer_content()
    {
        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            Prompt?

            ### Answer

            First part.

            ### Answer

            Second part.
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        var question = Assert.Single(result.Attempt.Questions);
        Assert.Contains("First part.", question.Answer);
        Assert.Contains("Second part.", question.Answer);
    }

    [Fact]
    public void A_generated_assessment_round_trips_into_an_unanswered_attempt()
    {
        var assessment = new Assessment(
            "C# Assessment",
            new DateTimeOffset(2026, 7, 17, 18, 0, 0, TimeSpan.Zero),
            [
                new AssessmentQuestion("What is boxing in C#?"),
                new AssessmentQuestion("Explain garbage collection generations."),
            ]);

        var rendered = new AssessmentRenderer().Render(assessment, "assessment-2026-07-17-001");
        var result = _parser.Parse(rendered);

        Assert.True(result.IsValid);
        Assert.Equal(assessment.Title, result.Attempt.Title);
        Assert.Equal(assessment.CreatedAtUtc, result.Attempt.CreatedAtUtc);
        Assert.Equal("assessment-2026-07-17-001", result.Attempt.AssessmentId);
        Assert.Equal(
            assessment.Questions.Select(question => question.Prompt),
            result.Attempt.Questions.Select(question => question.Prompt));
        Assert.All(result.Attempt.Questions, question => Assert.False(question.IsAnswered));
    }

    [Fact]
    public void Accepts_the_full_generated_assessment_metadata()
    {
        var markdown =
            """
            ---
            type: assessment
            id: assessment-2026-07-17-001
            title: C# Assessment
            created: 2026-07-17T09:30:00
            question_count: 1
            ---

            ## Question 1

            What is boxing in C#?

            ### Answer

            Boxing wraps a value type in an object.
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Empty(result.Diagnostics);
        Assert.Equal("assessment-2026-07-17-001", result.Attempt.AssessmentId);
    }

    [Fact]
    public void An_explicit_assessment_reference_is_the_assessment_identity()
    {
        var markdown =
            """
            ---
            type: assessment
            assessment: assessment-2026-07-17-001
            created: 2026-07-17T10:15:00
            ---

            # C# Assessment

            ## Question 1

            What is boxing in C#?

            ### Answer

            An answer.
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Equal("assessment-2026-07-17-001", result.Attempt.AssessmentId);
    }

    [Fact]
    public void An_explicit_assessment_reference_wins_over_the_id_field()
    {
        var markdown =
            """
            ---
            type: assessment
            id: some-other-id
            assessment: assessment-2026-07-17-001
            title: C# Assessment
            created: 2026-07-17T10:15:00
            ---

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Equal("assessment-2026-07-17-001", result.Attempt.AssessmentId);
    }

    [Fact]
    public void Assessment_identity_is_optional()
    {
        var markdown =
            $"""
            {Frontmatter}

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.True(result.IsValid);
        Assert.Null(result.Attempt.AssessmentId);
    }

    [Fact]
    public void The_assessment_attempt_type_is_not_supported()
    {
        var markdown =
            """
            ---
            type: assessment-attempt
            title: C# Assessment
            created: 2026-07-17T10:15:00
            ---

            ## Question 1

            Prompt?

            ### Answer
            """;

        var result = _parser.Parse(markdown);

        Assert.False(result.IsValid);
        Assert.Contains(result.Diagnostics, diagnostic =>
            diagnostic.Message.Contains("Unexpected document type 'assessment-attempt'"));
    }
}
