using RecallCommander.Application.Artifacts;
using RecallCommander.Domain;

namespace RecallCommander.Markdown.Writing;

/// <summary>
/// Renders an <see cref="Assessment"/> as a readable Markdown document.
/// Only the question prompts appear; types, concepts and reference answers
/// are never part of the generated assessment. Every question ends with an
/// empty '### Answer' heading, ready for the user to fill in when turning a
/// saved copy of the assessment into an attempt.
/// </summary>
public sealed class AssessmentRenderer : IArtifactRenderer<Assessment>
{
    public string Slug => "assessment";

    public string DirectoryName => "Assessments";

    public string Render(Assessment assessment, string artifactId)
    {
        var builder = new MarkdownArtifactBuilder()
            .WithFrontmatter(new AssessmentFrontmatter(
                Slug,
                artifactId,
                assessment.Title,
                assessment.CreatedAtUtc,
                assessment.Questions.Count))
            .AppendHeading(1, assessment.Title)
            .AppendMarkdown("This assessment was generated by Recall Commander.");

        for (var index = 0; index < assessment.Questions.Count; index++)
        {
            builder
                .AppendThematicBreak()
                .AppendHeading(2, $"Question {index + 1}")
                .AppendMarkdown(assessment.Questions[index].Prompt)
                .AppendHeading(3, "Answer");
        }

        return builder.Build();
    }

    private sealed record AssessmentFrontmatter(
        string Type,
        string Id,
        string Title,
        DateTimeOffset Created,
        int QuestionCount);
}
