using RecallCommander.Application.Artifacts;
using RecallCommander.Domain;

namespace RecallCommander.Markdown.Writing;

/// <summary>
/// Renders an <see cref="Assessment"/> as a readable Markdown document.
/// Only the question prompts appear; types, concepts and reference answers
/// are never part of the generated assessment.
/// </summary>
public sealed class AssessmentRenderer : IArtifactRenderer<Assessment>
{
    private const string Slug = "assessment";
    private const string DirectoryName = "Assessments";

    public ArtifactContent Render(Assessment assessment)
    {
        var builder = new MarkdownArtifactBuilder()
            .WithFrontmatter(new AssessmentFrontmatter(
                Slug,
                assessment.Title,
                assessment.CreatedAtUtc,
                assessment.Questions.Count))
            .AppendHeading(1, assessment.Title)
            .AppendMarkdown("This assessment was generated by Recall Commander.");

        for (var index = 0; index < assessment.Questions.Count; index++)
        {
            builder
                .AppendThematicBreak()
                .AppendHeading(2, $"Question {index + 1}")
                .AppendMarkdown(assessment.Questions[index].Prompt);
        }

        return new ArtifactContent(Slug, DirectoryName, builder.Build());
    }

    private sealed record AssessmentFrontmatter(
        string Type,
        string Title,
        DateTimeOffset Created,
        int QuestionCount);
}
